# 头部菜单，title: link
menu:
  # Whoami: /whoami
  Github: https://github.com/zsgdyf
  Twitter: https://twitter.com/zsgdyf
  分类: /categories
  归档: /archives
  标签云: /tags

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/5146554.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover1.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '6343f9028efd0476e771'
    # 应用秘钥
    clientSecret: 'd06ca503cc9e12a08d5323e3ead1f57b6512cff3'
    # issue仓库名
    repo: 'zsgdyf.github.io'
    # Github名
    owner: 'zsgdyf'
    # Github名
    admin: ['zsgdyf']
    # Ensure uniqueness and length less than 50
    id: zsgdyf
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: zsgdyf

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-126218656-1

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
